<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <DefaultItemExcludes>$(DefaultItemExcludes);QuanLySinhVien\**</DefaultItemExcludes>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="QuanLySinhVien\**" />
    <EmbeddedResource Remove="QuanLySinhVien\**" />
    <None Remove="QuanLySinhVien\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="EPPlus" Version="8.6.3" />
    <PackageReference Include="itext7" Version="9.7.0" />
    <PackageReference Include="Microsoft.Data.SqlClient" Version="7.0.2" />
    <PackageReference Include="WinForms.DataVisualization" Version="1.10.2" />
  </ItemGroup>

</Project>